/**:
  ros__parameters:
    motions:
      home:
        joints: [torso_lift_joint]
        times_from_start: [3.0]
        positions: [0.15]
        meta:
          name: Home
          usage: demo
          description: 'Go home'

      torso_up:
        joints: [torso_lift_joint]
        positions: [0.33]
        times_from_start: [5.0]
        meta:
          name: Torso Up
          usage: Demo
          description: torso up

      torso_down:
        joints: [torso_lift_joint]
        positions: [0.02]
        times_from_start: [0.0]
        meta:
          name: Torso Down
          usage: Demo
          description: torso down

