${ARM_SIDE_PREFIX}_cartesian_space_controller_ee_frame:
  ros__parameters:
    type: tsid_controllers/CartesianSpaceController
    update_rate: 1000
    local_frame: true
    
    joint_state_names:
      - ${ARM_SIDE_PREFIX}_1_joint
      - ${ARM_SIDE_PREFIX}_2_joint
      - ${ARM_SIDE_PREFIX}_3_joint
      - ${ARM_SIDE_PREFIX}_4_joint
      - ${ARM_SIDE_PREFIX}_5_joint
      - ${ARM_SIDE_PREFIX}_6_joint
      - ${ARM_SIDE_PREFIX}_7_joint

    joint_command_names:
      - ${ARM_SIDE_PREFIX}_1_joint
      - ${ARM_SIDE_PREFIX}_2_joint
      - ${ARM_SIDE_PREFIX}_3_joint
      - ${ARM_SIDE_PREFIX}_4_joint
      - ${ARM_SIDE_PREFIX}_5_joint
      - ${ARM_SIDE_PREFIX}_6_joint
      - ${ARM_SIDE_PREFIX}_7_joint

    interface_name: position

    ee_names:
      - ${ARM_SIDE_PREFIX}_7_link

    ee_vmax: 0.15

    velocity_scaling: 1.0

    manipulation_cube:
         arm_right_7_link:      
          x_min: -0.2
          x_max: 1.0
          y_min: -0.705
          y_max: 0.22
          z_min: 0.0
          z_max: 1.49
         arm_left_7_link:      
          x_min: -0.2
          x_max: 1.0
          y_min: -0.22 
          y_max: 0.705      
          z_min: 0.0
          z_max: 1.49    
# # common manipulation cube
#          arm_right_7_link:      
#           x_min: 0.3
#           x_max: 0.8
#           y_min: -0.25
#           y_max: 0.25
#           z_min: 0.65
#           z_max: 1.15
#          arm_left_7_link:      
#           x_min: 0.3
#           x_max: 0.8
#           y_min: -0.25
#           y_max: 0.25
#           z_min: 0.65
#           z_max: 1.15   