${ARM_SIDE_PREFIX}_cartesian_vel_controller_ee_frame:
  ros__parameters:
    type: tsid_controllers/CartesianVelocityController
    
    joint_state_names:
      - ${ARM_SIDE_PREFIX}_1_joint
      - ${ARM_SIDE_PREFIX}_2_joint
      - ${ARM_SIDE_PREFIX}_3_joint
      - ${ARM_SIDE_PREFIX}_4_joint
      - ${ARM_SIDE_PREFIX}_5_joint
      - ${ARM_SIDE_PREFIX}_6_joint
      - ${ARM_SIDE_PREFIX}_7_joint

    joint_command_names:
      - ${ARM_SIDE_PREFIX}_1_joint
      - ${ARM_SIDE_PREFIX}_2_joint
      - ${ARM_SIDE_PREFIX}_3_joint
      - ${ARM_SIDE_PREFIX}_4_joint
      - ${ARM_SIDE_PREFIX}_5_joint
      - ${ARM_SIDE_PREFIX}_6_joint
      - ${ARM_SIDE_PREFIX}_7_joint

    interface_name: position

    ee_names:
      - ${ARM_SIDE_PREFIX}_7_link

    velocity_scaling: 1.0
    local_frame: true

    posture_gain: 1.0
    manipulation_cube:
         arm_right_7_link:      
          x_min: -0.2
          x_max: 0.7
          y_min: -0.75
          y_max: 0.22
          z_min: 0.0
          z_max: 1.4
         arm_left_7_link:      
          x_min: -0.2
          x_max: 0.7
          y_min: -0.22 
          y_max: 0.75   
          z_min: 0.0
          z_max: 1.4
         arm_head_7_link:      
          x_min: -0.5
          x_max: 0.7
          y_min: -0.75      
          y_max: 0.60  
          z_min: 0.6
          z_max: 1.7



