/**:
  ros__parameters:
    motions:
      close_right:
        joints: [gripper_right_finger_joint]
        positions: [0.935]
        times_from_start: [0.5]
        meta:
          name: Close Right Gripper
          usage: demo
          description: 'Closes right gripper'

      close_right_half:
        joints: [gripper_right_finger_joint]
        positions: [0.5]
        times_from_start: [0.5]
        meta:
          name: Close Right Gripper Half
          usage: demo
          description: 'Closes right gripper halfway'

      open_right:
        joints: [gripper_right_finger_joint]
        positions: [0.0]
        times_from_start: [0.5]
        meta:
          name: Open Right Gripper
          usage: demo
          description: 'Open right gripper'
