/**:
  ros__parameters:
    motions:
      home:
        joints: [torso_lift_joint, arm_right_1_joint, arm_right_2_joint, arm_right_3_joint, arm_right_4_joint, arm_right_5_joint, arm_right_6_joint, arm_right_7_joint]
        times_from_start: [0.0, 5.0, 10.0]
        positions: [0.17202, -1.8614, -1.6008, -0.34892, -1.9818, 0.10153, -1.2, 0.0,
                    0.1761, -0.26, -1.6008, -0.3489, -1.9818, -0.0, -1.2, 0.0,
                    0.1, -0.36, -1.83, -0.47, -2.35, -0.0, -1.2, 0.0]
        meta:
          name: home
          usage: demo
          description: home

      home_right:
        joints: [torso_lift_joint, arm_right_1_joint, arm_right_2_joint, arm_right_3_joint, arm_right_4_joint, arm_right_5_joint, arm_right_6_joint, arm_right_7_joint]
        times_from_start: [0.0, 5.0, 10.0]
        positions: [0.17202, -1.8614, -1.6008, -0.34892, -1.9818, 0.10153, -1.2, 0.0,
                    0.1761, -0.26, -1.6008, -0.3489, -1.9818, -0.0, -1.2, 0.0,
                    0.1, -0.36, -1.83, -0.47, -2.35, -0.0, -1.2, 0.0]
        meta:
          name: home_right
          usage: demo
          description: home_right

      wave_right:
        joints: [torso_lift_joint, arm_right_1_joint, arm_right_2_joint, arm_right_3_joint, arm_right_4_joint, arm_right_5_joint, arm_right_6_joint, arm_right_7_joint]
        times_from_start: [0.0, 3.0, 5.0, 7.0, 9.0, 11.0, 13.0]
        positions: [0.095, -1.5569, -1.5889, 0.32293, -2.0578, -0.11065, -0.91429, -1.86,
                    0.095, -1.2241, -1.228, 1.7545, -1.4439, -0.11162, -0.46424, -3.4051e-07,
                    0.095, -1.226, -1.2288, 1.7575, -2.0414, -0.11122, -0.49674, -0.00078511,
                    0.095, -1.2241, -1.228, 1.7545, -1.4439, -0.11162, -0.46424, -3.4051e-07,
                    0.095, -1.226, -1.2288, 1.7575, -2.0414, -0.11122, -0.49674, -0.00078511,
                    0.095, -1.2241, -1.228, 1.7545, -1.4439, -0.11162, -0.46424, -3.4051e-07,
                    0.095, -1.226, -1.2288, 1.7575, -2.0414, -0.11122, -0.49674, -0.00078511]
        meta:
          name: wave_right
          usage: demo
          description: wave_right

      wave_with_torso:
        joints: [torso_lift_joint, arm_right_1_joint, arm_right_2_joint, arm_right_3_joint, arm_right_4_joint, arm_right_5_joint, arm_right_6_joint, arm_right_7_joint]
        times_from_start: [0.0, 3.0, 5.0, 7.0, 9.0, 11.0, 13.0]
        positions: [0.075, -1.5569, -1.5889, 0.32293, -2.0578, -0.11065, -0.91429, -1.86,
                    0.075, -1.2241, -1.228, 1.7545, -1.4439, -0.11162, -0.46424, -3.4051e-07,
                    0.125, -1.226, -1.2288, 1.7575, -2.0414, -0.11122, -0.49674, -0.00078511,
                    0.075, -1.2241, -1.228, 1.7545, -1.4439, -0.11162, -0.46424, -3.4051e-07,
                    0.125, -1.226, -1.2288, 1.7575, -2.0414, -0.11122, -0.49674, -0.00078511,
                    0.075, -1.2241, -1.228, 1.7545, -1.4439, -0.11162, -0.46424, -3.4051e-07,
                    0.125, -1.226, -1.2288, 1.7575, -2.0414, -0.11122, -0.49674, -0.00078511]
        meta:
          name: wave_with_torso
          usage: demo
          description: wave_with_torso

      offer_right:
        joints: [torso_lift_joint, arm_right_1_joint, arm_right_2_joint, arm_right_3_joint, arm_right_4_joint, arm_right_5_joint, arm_right_6_joint, arm_right_7_joint]
        times_from_start: [0.0]
        positions: [0.14, 0.25843, -0.57522, -0.50314, -2.0337, 0.0, 1.0543, -1.5708]
        meta:
          name: offer_right
          usage: demo
          description: offer_right

      shake_right:
        joints: [torso_lift_joint, arm_right_1_joint, arm_right_2_joint, arm_right_3_joint, arm_right_4_joint, arm_right_5_joint, arm_right_6_joint, arm_right_7_joint]
        times_from_start: [0.0, 1.0, 2.5, 4.0, 5.5, 7.0]
        positions: [0.125, 0.25843, -0.57522, -0.50314, -2.0337, 0.0, 1.0612, 0.0,
                    0.125, 0.25843, -0.57522, -0.50314, -2.0337, 0.0, 0.8137, 0.0,
                    0.125, 0.25843, -0.57522, -0.50314, -2.0337, 0.0, 1.3237, 0.0,
                    0.125, 0.25843, -0.57522, -0.50314, -2.0337, 0.0, 0.8137, 0.0,
                    0.125, 0.25843, -0.57522, -0.50314, -2.0337, 0.0, 1.3237, 0.0,
                    0.125, 0.25843, -0.57522, -0.50314, -2.0337, 0.0, 1.0612, 0.0]
        meta:
          name: shake_right
          usage: demo
          description: shake_right

      horizontal_right:
          joints: [torso_lift_joint, arm_right_1_joint, arm_right_2_joint, arm_right_3_joint, arm_right_4_joint, arm_right_5_joint, arm_right_6_joint, arm_right_7_joint]
          positions: [0.23, -0.7167, -1.83, -0.1158, -2.35, -0.0, -1.2, 0.0,
            0.23, -1.75, -1.83, -0.47, -2.35, -0.0, -1.20, 0.0,
            0.23, -1.75, -1.27, 0.0, 0.0, 0.0, 0.0, 0.0,]
          times_from_start: [0.0, 3.0, 8.0]
          meta:
            name: Horizontal Right
            usage: Demo
            description: horizontal right

      reach_floor_right:
        joints: [torso_lift_joint, arm_right_1_joint, arm_right_2_joint, arm_right_3_joint, arm_right_4_joint, arm_right_5_joint, arm_right_6_joint, arm_right_7_joint, head_1_joint, head_2_joint]
        positions: [0.25, -0.36, -1.83, -0.47, -2.35, -0.0, -1.20, 0.0,  -0.7, 0.0,
                    0.25, -0.36, -0.73997, 0.3, -0.26, 0.43571, -0.1, 0.0, 0.0, 0.0]
        times_from_start: [0.0, 5.0]
        meta:
          name: Reach Floor Right
          usage: Demo
          description: reach floor right

      torso_up:
        joints: [torso_lift_joint]
        positions: [0.33]
        times_from_start: [5.0]
        meta:
          name: Torso Up
          usage: Demo
          description: torso up

      torso_down:
        joints: [torso_lift_joint]
        positions: [0.02]
        times_from_start: [0.0]
        meta:
          name: Torso Down
          usage: Demo
          description: torso down

      boxing:
        joints: [torso_lift_joint, arm_right_1_joint, arm_right_2_joint, arm_right_3_joint, arm_right_4_joint, arm_right_5_joint, arm_right_6_joint, arm_right_7_joint]
        times_from_start: [0.0, 5.0, 10.0, 15.0]
        positions: [0.17202, -1.8614, -1.6008, -0.34892, -1.9818, 0.10153, -1.5829, 0.0,
                    0.1761, -0.26, -1.6008, -0.3489, -1.9818, -0.0, -1.5829, 0.0,
                    0.1, -0.36, -1.83, -0.47, -2.35, -0.0, -1.2, 0.0,
                    0.0, -0.29, -1.89, -0.48, -2.37, -0.2, -1.25, 1.71]
        meta:
          name: Boxing
          usage: demo
          description: Go boxing


