${ARM_SIDE_PREFIX}_forward_controller_vel:
  ros__parameters:
    type: velocity_controllers/JointGroupVelocityController
    update_rate: 1000
    
    joints:
      - ${ARM_SIDE_PREFIX}_1_joint
      - ${ARM_SIDE_PREFIX}_2_joint
      - ${ARM_SIDE_PREFIX}_3_joint
      - ${ARM_SIDE_PREFIX}_4_joint
      - ${ARM_SIDE_PREFIX}_5_joint
      - ${ARM_SIDE_PREFIX}_6_joint
      - ${ARM_SIDE_PREFIX}_7_joint

    interface_name: velocity