${ARM_SIDE_PREFIX}_cartesian_space_controller_robot_frame:
  ros__parameters:
    joint_pos_gain:
      ${ARM_SIDE_PREFIX}_1_joint:
        kp: 25.0
        kd: 110.0
      ${ARM_SIDE_PREFIX}_2_joint:
        kp: 25.0
        kd: 110.0
      ${ARM_SIDE_PREFIX}_3_joint:
        kp: 25.0
        kd: 110.0
      ${ARM_SIDE_PREFIX}_4_joint:
        kp: 25.0
        kd: 110.0
      ${ARM_SIDE_PREFIX}_5_joint:
        kp: 25.0
        kd: 110.0
      ${ARM_SIDE_PREFIX}_6_joint:
        kp: 25.0
        kd: 110.0
      ${ARM_SIDE_PREFIX}_7_joint:
        kp: 25.0
        kd: 110.0
    cartesian_gain:
      ${ARM_SIDE_PREFIX}_7_link:
        kp_x: 400.0
        kp_y: 400.0
        kp_z: 400.0
        kp_roll: 50.0
        kp_pitch: 50.0
        kp_yaw: 50.0
        kd_x: 1000.0
        kd_y: 1000.0
        kd_z: 1000.0
        kd_roll: 200.0
        kd_pitch: 200.0
        kd_yaw: 200.0