torso_joint_space_controller:
  ros__parameters:
    type: tsid_controllers/JointSpaceTsidController
    update_rate: 1000
    
    joint_state_names:
      - torso_lift_joint

    joint_command_names:
      - torso_lift_joint

    ee_names:
      - arm_right_7_link

    interface_name: position

    velocity_scaling: 1.0
    